### ISSUE TITLE
多多客ID,     'pid' 如何获得？

### ISSUE THREAD

**Issue by hqin2013** [yumufeng/pdd-union-sdk#1]
请问这两个ID如何获得？
`'ddkId' => '', // 多多客ID,
'pid' => '',`

谢谢

**Comment by yumufeng** [comment]
ddkId为多多客招商ID

PID为默认推广位ID

**Comment by hqin2013** [comment]
是的 ，找到了

ddkId 在  jinbao.pinduoduo.com  获取。
PID 可以通过接口生成。


> ddkId为多多客招商ID
> 
> PID为默认推广位ID
